index:
    path: /
    controller: App\Controller\HomeController::index

category_index:
    path: /category/{id}
    controller: App\Controller\ListController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::index
    requirements:
        id: '\d+'

product_add_vote:
    path: /product/{id}/vote
    methods:    POST
    controller: App\Controller\ProductController::addVote

product_add_to_cart:
    path: /product/{id}/add_to_cart
    methods:    POST
    controller: App\Controller\ProductController::addToCart

product_remove_from_cart:
    path: /product/{id}/remove_from_cart
    methods:    POST
    controller: App\Controller\ProductController::removeFromCart

product_update_count:
    path: /product/{id}/update_count
    methods:    POST
    controller: App\Controller\ProductController::updateItemCount

product_show_cart:
    path: /product/show_cart
    methods:    POST
    controller: App\Controller\ProductController::showCart

checkout:
    path: /checkout
    methods:    [GET, POST]
    controller: App\Controller\CheckoutController::index

page_contact_us:
    path: /contact_us
    methods:    [GET, POST]
    controller: App\Controller\PageController::contactUs

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_order_history:
    path: /order/history
    controller: App\Controller\CheckoutController::getOrdersHistory